# pyre-unsafe

from typing import List, Optional

from django.http import HttpRequest, HttpResponse
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View

class SingleObjectMixin(ContextMixin):
    def get_object(self, query_set=None): ...
    def get_queryset(self): ...
    def get_slug_field(self) -> str: ...
    def get_context_object_name(self, obj) -> Optional[str]: ...
    def get_context_data(self, **kwargs): ...

class BaseDetailView(SingleObjectMixin, View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse: ...

class SingleObjectTemplateResponseMixin(TemplateResponseMixin):
    template_name_field: Optional[str] = ...
    template_name_suffix: str = ...
    def get_template_name(self) -> List[str]: ...

class DetailView(SingleObjectTemplateResponseMixin, BaseDetailView):
    pass
